/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects_.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects_.$projectId'
import { Route as ProjectsProjectIdReviewRouteImport } from './routes/projects_.$projectId_.review'
import { Route as ProjectsProjectIdFactsRouteImport } from './routes/projects_.$projectId_.facts'
import { Route as ProjectsProjectIdEntitiesRouteImport } from './routes/projects_.$projectId_.entities'
import { Route as ProjectsProjectIdDocumentsRouteImport } from './routes/projects_.$projectId_.documents'
import { Route as ProjectsProjectIdAlertsRouteImport } from './routes/projects_.$projectId_.alerts'
import { Route as ProjectsProjectIdReviewIndexRouteImport } from './routes/projects_.$projectId_.review.index'
import { Route as ProjectsProjectIdDocumentsIndexRouteImport } from './routes/projects_.$projectId_.documents.index'
import { Route as ProjectsProjectIdReviewDocumentIdRouteImport } from './routes/projects_.$projectId_.review.$documentId'
import { Route as ProjectsProjectIdDocumentsNewRouteImport } from './routes/projects_.$projectId_.documents.new'
import { Route as ProjectsProjectIdDocumentsDocumentIdRouteImport } from './routes/projects_.$projectId_.documents.$documentId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects_/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdReviewRoute = ProjectsProjectIdReviewRouteImport.update({
  id: '/projects_/$projectId_/review',
  path: '/projects/$projectId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdFactsRoute = ProjectsProjectIdFactsRouteImport.update({
  id: '/projects_/$projectId_/facts',
  path: '/projects/$projectId/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEntitiesRoute =
  ProjectsProjectIdEntitiesRouteImport.update({
    id: '/projects_/$projectId_/entities',
    path: '/projects/$projectId/entities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdDocumentsRoute =
  ProjectsProjectIdDocumentsRouteImport.update({
    id: '/projects_/$projectId_/documents',
    path: '/projects/$projectId/documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdAlertsRoute = ProjectsProjectIdAlertsRouteImport.update({
  id: '/projects_/$projectId_/alerts',
  path: '/projects/$projectId/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdReviewIndexRoute =
  ProjectsProjectIdReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdReviewRoute,
  } as any)
const ProjectsProjectIdDocumentsIndexRoute =
  ProjectsProjectIdDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdDocumentsRoute,
  } as any)
const ProjectsProjectIdReviewDocumentIdRoute =
  ProjectsProjectIdReviewDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ProjectsProjectIdReviewRoute,
  } as any)
const ProjectsProjectIdDocumentsNewRoute =
  ProjectsProjectIdDocumentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProjectsProjectIdDocumentsRoute,
  } as any)
const ProjectsProjectIdDocumentsDocumentIdRoute =
  ProjectsProjectIdDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ProjectsProjectIdDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/alerts': typeof ProjectsProjectIdAlertsRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRouteWithChildren
  '/projects/$projectId/entities': typeof ProjectsProjectIdEntitiesRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRoute
  '/projects/$projectId/review': typeof ProjectsProjectIdReviewRouteWithChildren
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
  '/projects/$projectId/documents/new': typeof ProjectsProjectIdDocumentsNewRoute
  '/projects/$projectId/review/$documentId': typeof ProjectsProjectIdReviewDocumentIdRoute
  '/projects/$projectId/documents/': typeof ProjectsProjectIdDocumentsIndexRoute
  '/projects/$projectId/review/': typeof ProjectsProjectIdReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/alerts': typeof ProjectsProjectIdAlertsRoute
  '/projects/$projectId/entities': typeof ProjectsProjectIdEntitiesRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
  '/projects/$projectId/documents/new': typeof ProjectsProjectIdDocumentsNewRoute
  '/projects/$projectId/review/$documentId': typeof ProjectsProjectIdReviewDocumentIdRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsIndexRoute
  '/projects/$projectId/review': typeof ProjectsProjectIdReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRoute
  '/projects_/$projectId': typeof ProjectsProjectIdRoute
  '/projects_/new': typeof ProjectsNewRoute
  '/projects_/$projectId_/alerts': typeof ProjectsProjectIdAlertsRoute
  '/projects_/$projectId_/documents': typeof ProjectsProjectIdDocumentsRouteWithChildren
  '/projects_/$projectId_/entities': typeof ProjectsProjectIdEntitiesRoute
  '/projects_/$projectId_/facts': typeof ProjectsProjectIdFactsRoute
  '/projects_/$projectId_/review': typeof ProjectsProjectIdReviewRouteWithChildren
  '/projects_/$projectId_/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
  '/projects_/$projectId_/documents/new': typeof ProjectsProjectIdDocumentsNewRoute
  '/projects_/$projectId_/review/$documentId': typeof ProjectsProjectIdReviewDocumentIdRoute
  '/projects_/$projectId_/documents/': typeof ProjectsProjectIdDocumentsIndexRoute
  '/projects_/$projectId_/review/': typeof ProjectsProjectIdReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/alerts'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/entities'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/review'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/documents/new'
    | '/projects/$projectId/review/$documentId'
    | '/projects/$projectId/documents/'
    | '/projects/$projectId/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/alerts'
    | '/projects/$projectId/entities'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/documents/new'
    | '/projects/$projectId/review/$documentId'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/review'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/projects'
    | '/projects_/$projectId'
    | '/projects_/new'
    | '/projects_/$projectId_/alerts'
    | '/projects_/$projectId_/documents'
    | '/projects_/$projectId_/entities'
    | '/projects_/$projectId_/facts'
    | '/projects_/$projectId_/review'
    | '/projects_/$projectId_/documents/$documentId'
    | '/projects_/$projectId_/documents/new'
    | '/projects_/$projectId_/review/$documentId'
    | '/projects_/$projectId_/documents/'
    | '/projects_/$projectId_/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsProjectIdAlertsRoute: typeof ProjectsProjectIdAlertsRoute
  ProjectsProjectIdDocumentsRoute: typeof ProjectsProjectIdDocumentsRouteWithChildren
  ProjectsProjectIdEntitiesRoute: typeof ProjectsProjectIdEntitiesRoute
  ProjectsProjectIdFactsRoute: typeof ProjectsProjectIdFactsRoute
  ProjectsProjectIdReviewRoute: typeof ProjectsProjectIdReviewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/new': {
      id: '/projects_/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/review': {
      id: '/projects_/$projectId_/review'
      path: '/projects/$projectId/review'
      fullPath: '/projects/$projectId/review'
      preLoaderRoute: typeof ProjectsProjectIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/facts': {
      id: '/projects_/$projectId_/facts'
      path: '/projects/$projectId/facts'
      fullPath: '/projects/$projectId/facts'
      preLoaderRoute: typeof ProjectsProjectIdFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/entities': {
      id: '/projects_/$projectId_/entities'
      path: '/projects/$projectId/entities'
      fullPath: '/projects/$projectId/entities'
      preLoaderRoute: typeof ProjectsProjectIdEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/documents': {
      id: '/projects_/$projectId_/documents'
      path: '/projects/$projectId/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/alerts': {
      id: '/projects_/$projectId_/alerts'
      path: '/projects/$projectId/alerts'
      fullPath: '/projects/$projectId/alerts'
      preLoaderRoute: typeof ProjectsProjectIdAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/review/': {
      id: '/projects_/$projectId_/review/'
      path: '/'
      fullPath: '/projects/$projectId/review/'
      preLoaderRoute: typeof ProjectsProjectIdReviewIndexRouteImport
      parentRoute: typeof ProjectsProjectIdReviewRoute
    }
    '/projects_/$projectId_/documents/': {
      id: '/projects_/$projectId_/documents/'
      path: '/'
      fullPath: '/projects/$projectId/documents/'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdDocumentsRoute
    }
    '/projects_/$projectId_/review/$documentId': {
      id: '/projects_/$projectId_/review/$documentId'
      path: '/$documentId'
      fullPath: '/projects/$projectId/review/$documentId'
      preLoaderRoute: typeof ProjectsProjectIdReviewDocumentIdRouteImport
      parentRoute: typeof ProjectsProjectIdReviewRoute
    }
    '/projects_/$projectId_/documents/new': {
      id: '/projects_/$projectId_/documents/new'
      path: '/new'
      fullPath: '/projects/$projectId/documents/new'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsNewRouteImport
      parentRoute: typeof ProjectsProjectIdDocumentsRoute
    }
    '/projects_/$projectId_/documents/$documentId': {
      id: '/projects_/$projectId_/documents/$documentId'
      path: '/$documentId'
      fullPath: '/projects/$projectId/documents/$documentId'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsDocumentIdRouteImport
      parentRoute: typeof ProjectsProjectIdDocumentsRoute
    }
  }
}

interface ProjectsProjectIdDocumentsRouteChildren {
  ProjectsProjectIdDocumentsDocumentIdRoute: typeof ProjectsProjectIdDocumentsDocumentIdRoute
  ProjectsProjectIdDocumentsNewRoute: typeof ProjectsProjectIdDocumentsNewRoute
  ProjectsProjectIdDocumentsIndexRoute: typeof ProjectsProjectIdDocumentsIndexRoute
}

const ProjectsProjectIdDocumentsRouteChildren: ProjectsProjectIdDocumentsRouteChildren =
  {
    ProjectsProjectIdDocumentsDocumentIdRoute:
      ProjectsProjectIdDocumentsDocumentIdRoute,
    ProjectsProjectIdDocumentsNewRoute: ProjectsProjectIdDocumentsNewRoute,
    ProjectsProjectIdDocumentsIndexRoute: ProjectsProjectIdDocumentsIndexRoute,
  }

const ProjectsProjectIdDocumentsRouteWithChildren =
  ProjectsProjectIdDocumentsRoute._addFileChildren(
    ProjectsProjectIdDocumentsRouteChildren,
  )

interface ProjectsProjectIdReviewRouteChildren {
  ProjectsProjectIdReviewDocumentIdRoute: typeof ProjectsProjectIdReviewDocumentIdRoute
  ProjectsProjectIdReviewIndexRoute: typeof ProjectsProjectIdReviewIndexRoute
}

const ProjectsProjectIdReviewRouteChildren: ProjectsProjectIdReviewRouteChildren =
  {
    ProjectsProjectIdReviewDocumentIdRoute:
      ProjectsProjectIdReviewDocumentIdRoute,
    ProjectsProjectIdReviewIndexRoute: ProjectsProjectIdReviewIndexRoute,
  }

const ProjectsProjectIdReviewRouteWithChildren =
  ProjectsProjectIdReviewRoute._addFileChildren(
    ProjectsProjectIdReviewRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsProjectIdAlertsRoute: ProjectsProjectIdAlertsRoute,
  ProjectsProjectIdDocumentsRoute: ProjectsProjectIdDocumentsRouteWithChildren,
  ProjectsProjectIdEntitiesRoute: ProjectsProjectIdEntitiesRoute,
  ProjectsProjectIdFactsRoute: ProjectsProjectIdFactsRoute,
  ProjectsProjectIdReviewRoute: ProjectsProjectIdReviewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
