/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as VellumChatRouteImport } from './routes/vellum.chat'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities.$entityId'
import { Route as DevChatRouteImport } from './routes/dev.chat'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdFactsRouteImport } from './routes/projects/$projectId/facts'
import { Route as ProjectsProjectIdEntitiesRouteImport } from './routes/projects/$projectId/entities'
import { Route as ProjectsProjectIdReviewRouteRouteImport } from './routes/projects/$projectId/review/route'
import { Route as ProjectsProjectIdDocumentsRouteRouteImport } from './routes/projects/$projectId/documents/route'
import { Route as ProjectsProjectIdCanonRouteRouteImport } from './routes/projects/$projectId/canon/route'
import { Route as ProjectsProjectIdAlertsRouteRouteImport } from './routes/projects/$projectId/alerts/route'
import { Route as ProjectsProjectIdReviewIndexRouteImport } from './routes/projects/$projectId/review/index'
import { Route as ProjectsProjectIdNotesIndexRouteImport } from './routes/projects/$projectId/notes/index'
import { Route as ProjectsProjectIdDocumentsIndexRouteImport } from './routes/projects/$projectId/documents/index'
import { Route as ProjectsProjectIdCanonIndexRouteImport } from './routes/projects/$projectId/canon/index'
import { Route as ProjectsProjectIdReviewDocumentIdRouteImport } from './routes/projects/$projectId/review/$documentId'
import { Route as ProjectsProjectIdNotesNewRouteImport } from './routes/projects/$projectId/notes/new'
import { Route as ProjectsProjectIdNotesNoteIdRouteImport } from './routes/projects/$projectId/notes/$noteId'
import { Route as ProjectsProjectIdDocumentsNewRouteImport } from './routes/projects/$projectId/documents/new'
import { Route as ProjectsProjectIdDocumentsDocumentIdRouteImport } from './routes/projects/$projectId/documents/$documentId'
import { Route as ProjectsProjectIdCanonTimelineRouteImport } from './routes/projects/$projectId/canon/timeline'
import { Route as ProjectsProjectIdCanonSearchRouteImport } from './routes/projects/$projectId/canon/search'
import { Route as ProjectsProjectIdCanonConnectionsRouteImport } from './routes/projects/$projectId/canon/connections'
import { Route as ProjectsProjectIdAlertsAlertIdRouteImport } from './routes/projects/$projectId/alerts/$alertId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const VellumChatRoute = VellumChatRouteImport.update({
  id: '/vellum/chat',
  path: '/vellum/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/entities/$entityId',
  path: '/entities/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevChatRoute = DevChatRouteImport.update({
  id: '/dev/chat',
  path: '/dev/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdFactsRoute = ProjectsProjectIdFactsRouteImport.update({
  id: '/$projectId/facts',
  path: '/$projectId/facts',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdEntitiesRoute =
  ProjectsProjectIdEntitiesRouteImport.update({
    id: '/$projectId/entities',
    path: '/$projectId/entities',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdReviewRouteRoute =
  ProjectsProjectIdReviewRouteRouteImport.update({
    id: '/$projectId/review',
    path: '/$projectId/review',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdDocumentsRouteRoute =
  ProjectsProjectIdDocumentsRouteRouteImport.update({
    id: '/$projectId/documents',
    path: '/$projectId/documents',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdCanonRouteRoute =
  ProjectsProjectIdCanonRouteRouteImport.update({
    id: '/$projectId/canon',
    path: '/$projectId/canon',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdAlertsRouteRoute =
  ProjectsProjectIdAlertsRouteRouteImport.update({
    id: '/$projectId/alerts',
    path: '/$projectId/alerts',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdReviewIndexRoute =
  ProjectsProjectIdReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdReviewRouteRoute,
  } as any)
const ProjectsProjectIdNotesIndexRoute =
  ProjectsProjectIdNotesIndexRouteImport.update({
    id: '/$projectId/notes/',
    path: '/$projectId/notes/',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdDocumentsIndexRoute =
  ProjectsProjectIdDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdDocumentsRouteRoute,
  } as any)
const ProjectsProjectIdCanonIndexRoute =
  ProjectsProjectIdCanonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdCanonRouteRoute,
  } as any)
const ProjectsProjectIdReviewDocumentIdRoute =
  ProjectsProjectIdReviewDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ProjectsProjectIdReviewRouteRoute,
  } as any)
const ProjectsProjectIdNotesNewRoute =
  ProjectsProjectIdNotesNewRouteImport.update({
    id: '/$projectId/notes/new',
    path: '/$projectId/notes/new',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdNotesNoteIdRoute =
  ProjectsProjectIdNotesNoteIdRouteImport.update({
    id: '/$projectId/notes/$noteId',
    path: '/$projectId/notes/$noteId',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsProjectIdDocumentsNewRoute =
  ProjectsProjectIdDocumentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProjectsProjectIdDocumentsRouteRoute,
  } as any)
const ProjectsProjectIdDocumentsDocumentIdRoute =
  ProjectsProjectIdDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ProjectsProjectIdDocumentsRouteRoute,
  } as any)
const ProjectsProjectIdCanonTimelineRoute =
  ProjectsProjectIdCanonTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => ProjectsProjectIdCanonRouteRoute,
  } as any)
const ProjectsProjectIdCanonSearchRoute =
  ProjectsProjectIdCanonSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => ProjectsProjectIdCanonRouteRoute,
  } as any)
const ProjectsProjectIdCanonConnectionsRoute =
  ProjectsProjectIdCanonConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => ProjectsProjectIdCanonRouteRoute,
  } as any)
const ProjectsProjectIdAlertsAlertIdRoute =
  ProjectsProjectIdAlertsAlertIdRouteImport.update({
    id: '/$alertId',
    path: '/$alertId',
    getParentRoute: () => ProjectsProjectIdAlertsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/dev/chat': typeof DevChatRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/vellum/chat': typeof VellumChatRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/alerts': typeof ProjectsProjectIdAlertsRouteRouteWithChildren
  '/projects/$projectId/canon': typeof ProjectsProjectIdCanonRouteRouteWithChildren
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRouteRouteWithChildren
  '/projects/$projectId/review': typeof ProjectsProjectIdReviewRouteRouteWithChildren
  '/projects/$projectId/entities': typeof ProjectsProjectIdEntitiesRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/alerts/$alertId': typeof ProjectsProjectIdAlertsAlertIdRoute
  '/projects/$projectId/canon/connections': typeof ProjectsProjectIdCanonConnectionsRoute
  '/projects/$projectId/canon/search': typeof ProjectsProjectIdCanonSearchRoute
  '/projects/$projectId/canon/timeline': typeof ProjectsProjectIdCanonTimelineRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
  '/projects/$projectId/documents/new': typeof ProjectsProjectIdDocumentsNewRoute
  '/projects/$projectId/notes/$noteId': typeof ProjectsProjectIdNotesNoteIdRoute
  '/projects/$projectId/notes/new': typeof ProjectsProjectIdNotesNewRoute
  '/projects/$projectId/review/$documentId': typeof ProjectsProjectIdReviewDocumentIdRoute
  '/projects/$projectId/canon/': typeof ProjectsProjectIdCanonIndexRoute
  '/projects/$projectId/documents/': typeof ProjectsProjectIdDocumentsIndexRoute
  '/projects/$projectId/notes': typeof ProjectsProjectIdNotesIndexRoute
  '/projects/$projectId/review/': typeof ProjectsProjectIdReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev/chat': typeof DevChatRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/vellum/chat': typeof VellumChatRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/alerts': typeof ProjectsProjectIdAlertsRouteRouteWithChildren
  '/projects/$projectId/entities': typeof ProjectsProjectIdEntitiesRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/alerts/$alertId': typeof ProjectsProjectIdAlertsAlertIdRoute
  '/projects/$projectId/canon/connections': typeof ProjectsProjectIdCanonConnectionsRoute
  '/projects/$projectId/canon/search': typeof ProjectsProjectIdCanonSearchRoute
  '/projects/$projectId/canon/timeline': typeof ProjectsProjectIdCanonTimelineRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
  '/projects/$projectId/documents/new': typeof ProjectsProjectIdDocumentsNewRoute
  '/projects/$projectId/notes/$noteId': typeof ProjectsProjectIdNotesNoteIdRoute
  '/projects/$projectId/notes/new': typeof ProjectsProjectIdNotesNewRoute
  '/projects/$projectId/review/$documentId': typeof ProjectsProjectIdReviewDocumentIdRoute
  '/projects/$projectId/canon': typeof ProjectsProjectIdCanonIndexRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsIndexRoute
  '/projects/$projectId/notes': typeof ProjectsProjectIdNotesIndexRoute
  '/projects/$projectId/review': typeof ProjectsProjectIdReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/dev/chat': typeof DevChatRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/vellum/chat': typeof VellumChatRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/alerts': typeof ProjectsProjectIdAlertsRouteRouteWithChildren
  '/projects/$projectId/canon': typeof ProjectsProjectIdCanonRouteRouteWithChildren
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRouteRouteWithChildren
  '/projects/$projectId/review': typeof ProjectsProjectIdReviewRouteRouteWithChildren
  '/projects/$projectId/entities': typeof ProjectsProjectIdEntitiesRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/alerts/$alertId': typeof ProjectsProjectIdAlertsAlertIdRoute
  '/projects/$projectId/canon/connections': typeof ProjectsProjectIdCanonConnectionsRoute
  '/projects/$projectId/canon/search': typeof ProjectsProjectIdCanonSearchRoute
  '/projects/$projectId/canon/timeline': typeof ProjectsProjectIdCanonTimelineRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
  '/projects/$projectId/documents/new': typeof ProjectsProjectIdDocumentsNewRoute
  '/projects/$projectId/notes/$noteId': typeof ProjectsProjectIdNotesNoteIdRoute
  '/projects/$projectId/notes/new': typeof ProjectsProjectIdNotesNewRoute
  '/projects/$projectId/review/$documentId': typeof ProjectsProjectIdReviewDocumentIdRoute
  '/projects/$projectId/canon/': typeof ProjectsProjectIdCanonIndexRoute
  '/projects/$projectId/documents/': typeof ProjectsProjectIdDocumentsIndexRoute
  '/projects/$projectId/notes/': typeof ProjectsProjectIdNotesIndexRoute
  '/projects/$projectId/review/': typeof ProjectsProjectIdReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projects'
    | '/dev/chat'
    | '/entities/$entityId'
    | '/vellum/chat'
    | '/projects/'
    | '/projects/$projectId/alerts'
    | '/projects/$projectId/canon'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/review'
    | '/projects/$projectId/entities'
    | '/projects/$projectId/facts'
    | '/projects/$projectId'
    | '/projects/$projectId/alerts/$alertId'
    | '/projects/$projectId/canon/connections'
    | '/projects/$projectId/canon/search'
    | '/projects/$projectId/canon/timeline'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/documents/new'
    | '/projects/$projectId/notes/$noteId'
    | '/projects/$projectId/notes/new'
    | '/projects/$projectId/review/$documentId'
    | '/projects/$projectId/canon/'
    | '/projects/$projectId/documents/'
    | '/projects/$projectId/notes'
    | '/projects/$projectId/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dev/chat'
    | '/entities/$entityId'
    | '/vellum/chat'
    | '/projects'
    | '/projects/$projectId/alerts'
    | '/projects/$projectId/entities'
    | '/projects/$projectId/facts'
    | '/projects/$projectId'
    | '/projects/$projectId/alerts/$alertId'
    | '/projects/$projectId/canon/connections'
    | '/projects/$projectId/canon/search'
    | '/projects/$projectId/canon/timeline'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/documents/new'
    | '/projects/$projectId/notes/$noteId'
    | '/projects/$projectId/notes/new'
    | '/projects/$projectId/review/$documentId'
    | '/projects/$projectId/canon'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/notes'
    | '/projects/$projectId/review'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/projects'
    | '/dev/chat'
    | '/entities/$entityId'
    | '/vellum/chat'
    | '/projects/'
    | '/projects/$projectId/alerts'
    | '/projects/$projectId/canon'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/review'
    | '/projects/$projectId/entities'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/'
    | '/projects/$projectId/alerts/$alertId'
    | '/projects/$projectId/canon/connections'
    | '/projects/$projectId/canon/search'
    | '/projects/$projectId/canon/timeline'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/documents/new'
    | '/projects/$projectId/notes/$noteId'
    | '/projects/$projectId/notes/new'
    | '/projects/$projectId/review/$documentId'
    | '/projects/$projectId/canon/'
    | '/projects/$projectId/documents/'
    | '/projects/$projectId/notes/'
    | '/projects/$projectId/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  DevChatRoute: typeof DevChatRoute
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
  VellumChatRoute: typeof VellumChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/vellum/chat': {
      id: '/vellum/chat'
      path: '/vellum/chat'
      fullPath: '/vellum/chat'
      preLoaderRoute: typeof VellumChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/chat': {
      id: '/dev/chat'
      path: '/dev/chat'
      fullPath: '/dev/chat'
      preLoaderRoute: typeof DevChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/facts': {
      id: '/projects/$projectId/facts'
      path: '/$projectId/facts'
      fullPath: '/projects/$projectId/facts'
      preLoaderRoute: typeof ProjectsProjectIdFactsRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/entities': {
      id: '/projects/$projectId/entities'
      path: '/$projectId/entities'
      fullPath: '/projects/$projectId/entities'
      preLoaderRoute: typeof ProjectsProjectIdEntitiesRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/review': {
      id: '/projects/$projectId/review'
      path: '/$projectId/review'
      fullPath: '/projects/$projectId/review'
      preLoaderRoute: typeof ProjectsProjectIdReviewRouteRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/$projectId/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/canon': {
      id: '/projects/$projectId/canon'
      path: '/$projectId/canon'
      fullPath: '/projects/$projectId/canon'
      preLoaderRoute: typeof ProjectsProjectIdCanonRouteRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/alerts': {
      id: '/projects/$projectId/alerts'
      path: '/$projectId/alerts'
      fullPath: '/projects/$projectId/alerts'
      preLoaderRoute: typeof ProjectsProjectIdAlertsRouteRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/review/': {
      id: '/projects/$projectId/review/'
      path: '/'
      fullPath: '/projects/$projectId/review/'
      preLoaderRoute: typeof ProjectsProjectIdReviewIndexRouteImport
      parentRoute: typeof ProjectsProjectIdReviewRouteRoute
    }
    '/projects/$projectId/notes/': {
      id: '/projects/$projectId/notes/'
      path: '/$projectId/notes'
      fullPath: '/projects/$projectId/notes'
      preLoaderRoute: typeof ProjectsProjectIdNotesIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/documents/': {
      id: '/projects/$projectId/documents/'
      path: '/'
      fullPath: '/projects/$projectId/documents/'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdDocumentsRouteRoute
    }
    '/projects/$projectId/canon/': {
      id: '/projects/$projectId/canon/'
      path: '/'
      fullPath: '/projects/$projectId/canon/'
      preLoaderRoute: typeof ProjectsProjectIdCanonIndexRouteImport
      parentRoute: typeof ProjectsProjectIdCanonRouteRoute
    }
    '/projects/$projectId/review/$documentId': {
      id: '/projects/$projectId/review/$documentId'
      path: '/$documentId'
      fullPath: '/projects/$projectId/review/$documentId'
      preLoaderRoute: typeof ProjectsProjectIdReviewDocumentIdRouteImport
      parentRoute: typeof ProjectsProjectIdReviewRouteRoute
    }
    '/projects/$projectId/notes/new': {
      id: '/projects/$projectId/notes/new'
      path: '/$projectId/notes/new'
      fullPath: '/projects/$projectId/notes/new'
      preLoaderRoute: typeof ProjectsProjectIdNotesNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/notes/$noteId': {
      id: '/projects/$projectId/notes/$noteId'
      path: '/$projectId/notes/$noteId'
      fullPath: '/projects/$projectId/notes/$noteId'
      preLoaderRoute: typeof ProjectsProjectIdNotesNoteIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/documents/new': {
      id: '/projects/$projectId/documents/new'
      path: '/new'
      fullPath: '/projects/$projectId/documents/new'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsNewRouteImport
      parentRoute: typeof ProjectsProjectIdDocumentsRouteRoute
    }
    '/projects/$projectId/documents/$documentId': {
      id: '/projects/$projectId/documents/$documentId'
      path: '/$documentId'
      fullPath: '/projects/$projectId/documents/$documentId'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsDocumentIdRouteImport
      parentRoute: typeof ProjectsProjectIdDocumentsRouteRoute
    }
    '/projects/$projectId/canon/timeline': {
      id: '/projects/$projectId/canon/timeline'
      path: '/timeline'
      fullPath: '/projects/$projectId/canon/timeline'
      preLoaderRoute: typeof ProjectsProjectIdCanonTimelineRouteImport
      parentRoute: typeof ProjectsProjectIdCanonRouteRoute
    }
    '/projects/$projectId/canon/search': {
      id: '/projects/$projectId/canon/search'
      path: '/search'
      fullPath: '/projects/$projectId/canon/search'
      preLoaderRoute: typeof ProjectsProjectIdCanonSearchRouteImport
      parentRoute: typeof ProjectsProjectIdCanonRouteRoute
    }
    '/projects/$projectId/canon/connections': {
      id: '/projects/$projectId/canon/connections'
      path: '/connections'
      fullPath: '/projects/$projectId/canon/connections'
      preLoaderRoute: typeof ProjectsProjectIdCanonConnectionsRouteImport
      parentRoute: typeof ProjectsProjectIdCanonRouteRoute
    }
    '/projects/$projectId/alerts/$alertId': {
      id: '/projects/$projectId/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/projects/$projectId/alerts/$alertId'
      preLoaderRoute: typeof ProjectsProjectIdAlertsAlertIdRouteImport
      parentRoute: typeof ProjectsProjectIdAlertsRouteRoute
    }
  }
}

interface ProjectsProjectIdAlertsRouteRouteChildren {
  ProjectsProjectIdAlertsAlertIdRoute: typeof ProjectsProjectIdAlertsAlertIdRoute
}

const ProjectsProjectIdAlertsRouteRouteChildren: ProjectsProjectIdAlertsRouteRouteChildren =
  {
    ProjectsProjectIdAlertsAlertIdRoute: ProjectsProjectIdAlertsAlertIdRoute,
  }

const ProjectsProjectIdAlertsRouteRouteWithChildren =
  ProjectsProjectIdAlertsRouteRoute._addFileChildren(
    ProjectsProjectIdAlertsRouteRouteChildren,
  )

interface ProjectsProjectIdCanonRouteRouteChildren {
  ProjectsProjectIdCanonConnectionsRoute: typeof ProjectsProjectIdCanonConnectionsRoute
  ProjectsProjectIdCanonSearchRoute: typeof ProjectsProjectIdCanonSearchRoute
  ProjectsProjectIdCanonTimelineRoute: typeof ProjectsProjectIdCanonTimelineRoute
  ProjectsProjectIdCanonIndexRoute: typeof ProjectsProjectIdCanonIndexRoute
}

const ProjectsProjectIdCanonRouteRouteChildren: ProjectsProjectIdCanonRouteRouteChildren =
  {
    ProjectsProjectIdCanonConnectionsRoute:
      ProjectsProjectIdCanonConnectionsRoute,
    ProjectsProjectIdCanonSearchRoute: ProjectsProjectIdCanonSearchRoute,
    ProjectsProjectIdCanonTimelineRoute: ProjectsProjectIdCanonTimelineRoute,
    ProjectsProjectIdCanonIndexRoute: ProjectsProjectIdCanonIndexRoute,
  }

const ProjectsProjectIdCanonRouteRouteWithChildren =
  ProjectsProjectIdCanonRouteRoute._addFileChildren(
    ProjectsProjectIdCanonRouteRouteChildren,
  )

interface ProjectsProjectIdDocumentsRouteRouteChildren {
  ProjectsProjectIdDocumentsDocumentIdRoute: typeof ProjectsProjectIdDocumentsDocumentIdRoute
  ProjectsProjectIdDocumentsNewRoute: typeof ProjectsProjectIdDocumentsNewRoute
  ProjectsProjectIdDocumentsIndexRoute: typeof ProjectsProjectIdDocumentsIndexRoute
}

const ProjectsProjectIdDocumentsRouteRouteChildren: ProjectsProjectIdDocumentsRouteRouteChildren =
  {
    ProjectsProjectIdDocumentsDocumentIdRoute:
      ProjectsProjectIdDocumentsDocumentIdRoute,
    ProjectsProjectIdDocumentsNewRoute: ProjectsProjectIdDocumentsNewRoute,
    ProjectsProjectIdDocumentsIndexRoute: ProjectsProjectIdDocumentsIndexRoute,
  }

const ProjectsProjectIdDocumentsRouteRouteWithChildren =
  ProjectsProjectIdDocumentsRouteRoute._addFileChildren(
    ProjectsProjectIdDocumentsRouteRouteChildren,
  )

interface ProjectsProjectIdReviewRouteRouteChildren {
  ProjectsProjectIdReviewDocumentIdRoute: typeof ProjectsProjectIdReviewDocumentIdRoute
  ProjectsProjectIdReviewIndexRoute: typeof ProjectsProjectIdReviewIndexRoute
}

const ProjectsProjectIdReviewRouteRouteChildren: ProjectsProjectIdReviewRouteRouteChildren =
  {
    ProjectsProjectIdReviewDocumentIdRoute:
      ProjectsProjectIdReviewDocumentIdRoute,
    ProjectsProjectIdReviewIndexRoute: ProjectsProjectIdReviewIndexRoute,
  }

const ProjectsProjectIdReviewRouteRouteWithChildren =
  ProjectsProjectIdReviewRouteRoute._addFileChildren(
    ProjectsProjectIdReviewRouteRouteChildren,
  )

interface ProjectsRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdAlertsRouteRoute: typeof ProjectsProjectIdAlertsRouteRouteWithChildren
  ProjectsProjectIdCanonRouteRoute: typeof ProjectsProjectIdCanonRouteRouteWithChildren
  ProjectsProjectIdDocumentsRouteRoute: typeof ProjectsProjectIdDocumentsRouteRouteWithChildren
  ProjectsProjectIdReviewRouteRoute: typeof ProjectsProjectIdReviewRouteRouteWithChildren
  ProjectsProjectIdEntitiesRoute: typeof ProjectsProjectIdEntitiesRoute
  ProjectsProjectIdFactsRoute: typeof ProjectsProjectIdFactsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdNotesNoteIdRoute: typeof ProjectsProjectIdNotesNoteIdRoute
  ProjectsProjectIdNotesNewRoute: typeof ProjectsProjectIdNotesNewRoute
  ProjectsProjectIdNotesIndexRoute: typeof ProjectsProjectIdNotesIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdAlertsRouteRoute:
    ProjectsProjectIdAlertsRouteRouteWithChildren,
  ProjectsProjectIdCanonRouteRoute:
    ProjectsProjectIdCanonRouteRouteWithChildren,
  ProjectsProjectIdDocumentsRouteRoute:
    ProjectsProjectIdDocumentsRouteRouteWithChildren,
  ProjectsProjectIdReviewRouteRoute:
    ProjectsProjectIdReviewRouteRouteWithChildren,
  ProjectsProjectIdEntitiesRoute: ProjectsProjectIdEntitiesRoute,
  ProjectsProjectIdFactsRoute: ProjectsProjectIdFactsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdNotesNoteIdRoute: ProjectsProjectIdNotesNoteIdRoute,
  ProjectsProjectIdNotesNewRoute: ProjectsProjectIdNotesNewRoute,
  ProjectsProjectIdNotesIndexRoute: ProjectsProjectIdNotesIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  DevChatRoute: DevChatRoute,
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
  VellumChatRoute: VellumChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
